name = "Priceless World Modpack"
author = "lithium514"
version = "26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23710ce4fcf1d679baff3984ac6a59e40dc63db8116bf7c6c2edcf484b85b6a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
